/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Tsukinami
 */
public class dataanggota extends javax.swing.JFrame {
    private DefaultTableModel Tabgota;
    Connection Con;
    
            private void LoadData(){
                Object kolom[] = {"NIS","N. SISWA","TTL","J.K","KELAS","ALAMAT","AGAMA","TGL DAFTAR","BERLAKU H"};
                Tabgota = new DefaultTableModel(null, kolom);
                Tabta.setModel(Tabgota);
                jScrollPane1.getViewport().add(Tabta,null);
                try{
                    Con = null;
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
                    String sql = "" + "SELECT * from anggota";
                    Statement stat = con.createStatement();
                    ResultSet res = stat.executeQuery(sql);
                    while(res.next()){
                        String NIS = res.getString("NIS");
                        String NamaSiswa = res.getString("Nama");
                        String TTL = res.getString("TempatTglLahir");
                        String JenisKelamin = res.getString("JenisKelamin");
                        String Kelas = res.getString("Kelas");
                        String Alamat = res.getString("Alamat");
                        String Agama = res.getString("Agama");
                        String TglDaftar = res.getString("TglPendaftaran");
                        String Berlaku = res.getString("BerlakuHingga");
                        Object[] data = {NIS, NamaSiswa, TTL, JenisKelamin, Kelas, Alamat, Agama, TglDaftar, Berlaku, };
                        Tabgota.addRow(data);
                    }
                    Tabta.getColumnModel().getColumn(0).setPreferredWidth(50);
                    Tabta.getColumnModel().getColumn(1).setPreferredWidth(80);
                    Tabta.getColumnModel().getColumn(2).setPreferredWidth(80);
                    Tabta.getColumnModel().getColumn(3).setPreferredWidth(20);
                    Tabta.getColumnModel().getColumn(4).setPreferredWidth(40);
                    Tabta.getColumnModel().getColumn(5).setPreferredWidth(80);
                    Tabta.getColumnModel().getColumn(6).setPreferredWidth(50);
                    Tabta.getColumnModel().getColumn(7).setPreferredWidth(80);
                    Tabta.getColumnModel().getColumn(8).setPreferredWidth(80);
                } catch (Exception ex){
                    JOptionPane.showMessageDialog(this,"Error: " + ex);
                }
            }
    /**
     * Creates new form dataanggota
     */
    public dataanggota() {
        initComponents();
        setLocationRelativeTo(null);
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJenisKelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NIS = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TTL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Agama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Behi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabta = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        RBLaki = new javax.swing.JRadioButton();
        RBPerempuan = new javax.swing.JRadioButton();
        CBKelas = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Data Anggota");

        jLabel2.setText("NIS");

        jLabel3.setText("Nama");

        NIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NISActionPerformed(evt);
            }
        });

        jLabel4.setText("Tempat/Tgl Lahir");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Kelas");

        jLabel7.setText("Agama");

        jLabel8.setText("Tgl. Daftar");

        jLabel9.setText("Berlaku Hingga");
        jLabel9.setToolTipText("");

        Tabta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabta);

        jButton1.setText("Search");

        edit.setText("Update");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setText("Alamat");

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane2.setViewportView(Alamat);

        btnJenisKelamin.add(RBLaki);
        RBLaki.setText("Laki-Laki");
        RBLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBLakiActionPerformed(evt);
            }
        });

        btnJenisKelamin.add(RBPerempuan);
        RBPerempuan.setText("Perempuan");

        CBKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "X", "XI", "XII" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(NIS, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(Nama)
                                            .addComponent(TTL)
                                            .addComponent(Agama)
                                            .addComponent(TD)
                                            .addComponent(Behi)
                                            .addComponent(jScrollPane2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(refresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RBLaki)
                                                .addGap(18, 18, 18)
                                                .addComponent(RBPerempuan))
                                            .addComponent(CBKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NIS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(refresh))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit)
                            .addComponent(delete))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(save)
                            .addComponent(jButton6)
                            .addComponent(TTL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RBLaki)))
                    .addComponent(RBPerempuan))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Agama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Behi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NISActionPerformed
        String x=NIS.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            Statement stat=connection.createStatement();
            String cari = "SELECT * FROM anggota WHERE NIS='"+x+"'";
            ResultSet rst=stat.executeQuery(cari);
            if(rst.next()){
                JOptionPane.showMessageDialog(null,"Data ditemukan");
                LoadData();
                System.out.print(rst.getString(1));
                NIS.setText(rst.getString(1));
                Nama.setText(rst.getString(2));
                TTL.setText(rst.getString(3));
                if (rst.getString(4).equals("Laki-Laki")){
                    RBLaki.setSelected(true);
                    }else{
                    RBPerempuan.setSelected(true);
                    }
                Alamat.setText(rst.getString(5));
                Agama.setText(rst.getString(6));
                TD.setText(rst.getString(7));
                Behi.setText(rst.getString(8));
                CBKelas.setSelectedItem(rst.getString(9));
        }else{
                JOptionPane.showMessageDialog(null,"Data tidak ada");
            }
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_NISActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null,"Yakin untuk mengubah data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            String sql="update anggota set nis=?,nama=?,tempattgllahir=?,jeniskelamin=?,alamat=?,agama=?,tglpendaftaran=?,berlakuhingga=?,kelas=? where nis='"+NIS.getText()+"'";
            PreparedStatement st=connection.prepareStatement(sql);
            if(confirm==0){
                try{
                    st.setString(1,NIS.getText());
                    st.setString(2,Nama.getText());
                    st.setString(3,TTL.getText());
                    if (RBLaki.isSelected()){
                    st.setString(4,RBLaki.getText());
                    }if(RBPerempuan.isSelected()){
                    st.setString(4,RBPerempuan.getText());
                    }
                    st.setString(5,Alamat.getText());
                    st.setString(6,Agama.getText());
                    st.setString(7,TD.getText());
                    st.setString(8,Behi.getText());
                    String skelas;
                    int kelas = CBKelas.getSelectedIndex();
                    if(kelas==0){st.setString(9,skelas="X");}
                    if(kelas==1){st.setString(9,skelas="XI");}
                    if(kelas==2){st.setString(9,skelas="XII");}
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Update Data Sukses");
                    LoadData();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Update Data Gagal");
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak ada Data");
        }
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
          try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");    
            Statement stat=connection.createStatement();
            String btnJenisKelamin="";
                if (RBLaki.isSelected()){
                    btnJenisKelamin = RBLaki.getText();
                }else{
                    btnJenisKelamin = RBPerempuan.getText();
                }
                int kelas = CBKelas.getSelectedIndex();
                String skelas = "";
                if(kelas==0){skelas="X";}
                if(kelas==1){skelas="XI";}
                if(kelas==2){skelas="XII";}
            String sqli=("insert into anggota values('"+NIS.getText()+"','"+Nama.getText()+"','"+TTL.getText()+"','"+btnJenisKelamin+"','"+Alamat.getText()+"','"+Agama.getText()+"','"+TD.getText()+"','"+Behi.getText()+"','"+skelas+"')");
            stat.executeUpdate(sqli);
            JOptionPane.showMessageDialog(null,"Data Tersimpan");
            LoadData();
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String x=NIS.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");    
            Statement stat=connection.createStatement();
            String sql="delete from anggota where nis='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data Telah terhapus");
            LoadData();
            NIS.setText(null);
            Nama.setText(null);
            TTL.setText(null);
            btnJenisKelamin.clearSelection();
            Alamat.setText(null);
            Agama.setText(null);
            TD.setText(null);
            Behi.setText(null);
            CBKelas.setSelectedIndex(0);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Koneksi Gagal"+e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        NIS.setText(null);
        Nama.setText(null);
        TTL.setText(null);
        btnJenisKelamin.clearSelection();
        Alamat.setText(null);
        Agama.setText(null);
        TD.setText(null);
        Behi.setText(null);
        CBKelas.setSelectedIndex(0);
    }//GEN-LAST:event_refreshActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Yakin untuk keluar?","Confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            this.dispose();
            new Menupetugas().show();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void RBLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBLakiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataanggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Agama;
    private javax.swing.JTextArea Alamat;
    private javax.swing.JTextField Behi;
    private javax.swing.JComboBox CBKelas;
    private javax.swing.JTextField NIS;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton RBLaki;
    private javax.swing.JRadioButton RBPerempuan;
    private javax.swing.JTextField TD;
    private javax.swing.JTextField TTL;
    private javax.swing.JTable Tabta;
    private javax.swing.ButtonGroup btnJenisKelamin;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
