/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tsukinami
 */
public class Peminjam extends javax.swing.JFrame {
    private DefaultTableModel Tabpin;
    Connection Con;
    
            private void LoadData(){
                    Object kolom[] = {"NIS","N. SISWA","KELAS","K.BUKU","N.BUKU","PENERBIT","TGL PINJAM","TGL KEMBALI","LAMA PINJAM"};
                Tabpin = new DefaultTableModel(null, kolom);
                Tapin.setModel(Tabpin);
                jScrollPane1.getViewport().add(Tapin,null);
                try{
                    Con = null;
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
                    String sql = "" + "SELECT * from datapinjam";
                    Statement stat = con.createStatement();
                    ResultSet res = stat.executeQuery(sql);
                    while(res.next()){
                        String NIS = res.getString("nis");
                        String NamaSiswa = res.getString("nama");
                        String Kelas = res.getString("kelas");
                        String KodeBuku = res.getString("kodebuku");
                        String NamaBuku = res.getString("namabuku");
                        String Penerbit = res.getString("penerbit");
                        String TglPinjam = res.getString("tanggalpinjam");
                        String TglKembali = res.getString("tanggalkembali");
                        String LamaPinjam = res.getString("LamaPinjam");
                        Object[] data = {NIS, NamaSiswa, Kelas, KodeBuku, NamaBuku, Penerbit, TglPinjam, TglKembali, LamaPinjam };
                        Tabpin.addRow(data);
                    }
                    Tapin.getColumnModel().getColumn(0).setPreferredWidth(50);
                    Tapin.getColumnModel().getColumn(1).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(2).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(3).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(4).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(5).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(6).setPreferredWidth(80);
                    Tapin.getColumnModel().getColumn(7).setPreferredWidth(80);
                    Tapin.getColumnModel().getColumn(8).setPreferredWidth(50);
                } catch (Exception ex){
                    JOptionPane.showMessageDialog(this,"Error: " + ex);
                }
            }
    /**
     * Creates new form Peminjam
     */
    public Peminjam() {
        initComponents();
        setLocationRelativeTo(null);
        Kelas.setEditable(false);
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nasis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Kelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        KB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Nabuk = new javax.swing.JTextField();
        Pen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TglPin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TglKem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nis = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        LamPin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tapin = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        kodepinjam = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Data Peminjam");

        jLabel2.setText("Nama");

        jLabel3.setText("Kelas");

        Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasActionPerformed(evt);
            }
        });

        jLabel4.setText("Kode Buku");

        jLabel5.setText("Nama Buku");

        jLabel6.setText("Penerbit");

        TglPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TglPinActionPerformed(evt);
            }
        });

        jLabel7.setText("Tgl. Pinjam");

        jLabel8.setText("Tgl. Kembali");

        TglKem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TglKemActionPerformed(evt);
            }
        });

        jLabel9.setText("NIS");

        jLabel10.setText("Lama Pinjam");

        Tapin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NAMA SISWA", "KELAS", "KODE BUKU", "NAMA BUKU", "PENERBIT", "TGL. PINJAM", "TGL. KEMBALI", "LAMA PINJAM"
            }
        ));
        jScrollPane1.setViewportView(Tapin);

        edit.setText("Update");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Date");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Kode Pinjam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(295, 295, 295))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nasis, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KB, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nabuk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TglPin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TglKem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addComponent(jButton5))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(kodepinjam)
                                    .addComponent(LamPin, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nis, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nasis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit)
                    .addComponent(delete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(KB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save)
                    .addComponent(jButton6)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Nabuk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TglPin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TglKem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(LamPin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodepinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null,"Yakin untuk mengubah data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            String sql="update datapinjam set nis=?,nama=?,kelas=?,kodebuku=?,namabuku=?,penerbit=?,tanggalpinjam=?,tanggalkembali=?,lamapinjam=?,kodepinjam=? where nis='"+nis.getText()+"'";
            PreparedStatement st=connection.prepareStatement(sql);
            if(confirm==0){
                try{
                    st.setString(1,nis.getText());
                    st.setString(2,Nasis.getText());
                    st.setString(3,Kelas.getText());
                    st.setString(4,KB.getText());
                    st.setString(5,Nabuk.getText());
                    st.setString(6,Pen.getText());
                    st.setString(7,TglPin.getText());
                    st.setString(8,TglKem.getText());
                    st.setString(9,LamPin.getText());
                    st.setString(10,kodepinjam.getText());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Update Data Sukses");
                    LoadData();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Update Data Gagal");
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak ada Data");
        }
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String x=nis.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");    
            Statement stat=connection.createStatement();
            String sqli=("insert into datapinjam values('"+nis.getText()+"','"+Nasis.getText()+"','"+Kelas.getText()+"','"+KB.getText()+"','"+Nabuk.getText()+"','"+Pen.getText()+"','"+TglPin.getText()+"','"+TglKem.getText()+"','"+LamPin.getText()+"','"+kodepinjam.getText()+"')");
            stat.executeUpdate(sqli);
            JOptionPane.showMessageDialog(null,"Data Tersimpan");
            LoadData();
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String x=nis.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");    
            Statement stat=connection.createStatement();
            String sql="delete from datapinjam where NIS='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data Telah terhapus");
            LoadData();
            nis.setText(null);
            Nasis.setText(null);
            Kelas.setText(null);
            KB.setText(null);
            Nabuk.setText("0");
            Pen.setText("0");
            TglPin.setText("0");
            TglKem.setText("0");
            LamPin.setText("0");
            kodepinjam.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Koneksi Gagal"+e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Yakin untuk keluar?","Confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            this.dispose();
            new Menupetugas().show();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        nis.setText(null);
        Nasis.setText(null);
        Kelas.setText(null);
        KB.setText(null);
        Nabuk.setText(null);
        Pen.setText(null);
        TglPin.setText("0");
        TglKem.setText("0");
        LamPin.setText("0");
        kodepinjam.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TglKemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TglKemActionPerformed
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        try{
            java.util.Date TanggalCEKIN = df.parse(TglPin.getText());
            java.util.Date TanggalCEKOUT = df.parse(TglKem.getText());
            
            long Hari1 = TanggalCEKIN.getTime();
            long Hari2 = TanggalCEKOUT.getTime();
            long diff = Hari2 - Hari1;
            Long lama = diff / (24*60*60*1000);
            LamPin.setText(Long.toString(lama) + " Hari");
        }catch(ParseException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_TglKemActionPerformed

    private void TglPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TglPinActionPerformed
        
    }//GEN-LAST:event_TglPinActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
        Calendar cal = Calendar.getInstance();
        TglPin.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String x = JOptionPane.showInputDialog(null,"Masukkan Nomor NIS");
         Kelas.setEditable(false);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            Statement stat=connection.createStatement();
            String cari = "SELECT * FROM datapinjam WHERE nis='"+x+"'";
            ResultSet rst=stat.executeQuery(cari);
            if(rst.next()){
                JOptionPane.showMessageDialog(null,"Data ditemukan");
                LoadData();
                System.out.print(rst.getString(1));
                nis.setText(rst.getString(1));
                Nasis.setText(rst.getString(2));
                Kelas.setText(rst.getString(3));
                KB.setText(rst.getString(4));
                Nabuk.setText(rst.getString(5));
                Pen.setText(rst.getString(6));
                TglPin.setText(rst.getString(7));
                TglKem.setText(rst.getString(8));
                LamPin.setText(rst.getString(9));
                kodepinjam.setText(rst.getString(10));
            }else{
                JOptionPane.showMessageDialog(null,"Data tidak ada");
            }
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String x=JOptionPane.showInputDialog(null, "Masukkan Kode NIS");
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            Statement stat = connection.createStatement();
            String cari = "SELECT nis, nama, kelas from anggota WHERE nis='"+x+"'";
            ResultSet rsnya= stat.executeQuery(cari);
            if(rsnya.next()){
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(null,"Data ditemukan");
                LoadData();
                nis.setText(rsnya.getString(1));
                Nasis.setText(rsnya.getString(2));
                Kelas.setText(rsnya.getString(3));
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String x=JOptionPane.showInputDialog(null, "Masukkan Kode Buku");
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            Statement stat = connection.createStatement();
            String cari = "SELECT kodebuku, namabuku, penerbit from databuku WHERE kodebuku='"+x+"'";
            ResultSet rsnya= stat.executeQuery(cari);
            if(rsnya.next()){
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(null,"Data ditemukan");
                LoadData();
                KB.setText(rsnya.getString(1));
                Nabuk.setText(rsnya.getString(2));
                Pen.setText(rsnya.getString(3));
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasActionPerformed
        Kelas.setEditable(false);
    }//GEN-LAST:event_KelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KB;
    private javax.swing.JTextField Kelas;
    private javax.swing.JTextField LamPin;
    private javax.swing.JTextField Nabuk;
    private javax.swing.JTextField Nasis;
    private javax.swing.JTextField Pen;
    private javax.swing.JTable Tapin;
    private javax.swing.JTextField TglKem;
    private javax.swing.JTextField TglPin;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodepinjam;
    private javax.swing.JTextField nis;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
