/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tsukinami
 */
public class pengembalian extends javax.swing.JFrame {
    private DefaultTableModel Tabpin;
    Connection Con;
    
            private void LoadData(){
                    Object kolom[] = {"KODE PINJAM","NIS","N. SISWA","KELAS","K.BUKU","N.BUKU","PENERBIT","TGL PINJAM","TGL KEMBALI","TGL PENGEMBALIAN","STATUS PENGEMBALIAN"};
                Tabpin = new DefaultTableModel(null, kolom);
                Tapin.setModel(Tabpin);
                jScrollPane1.getViewport().add(Tapin,null);
                try{
                    Con = null;
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
                    String sql = "" + "SELECT * from datakembali";
                    Statement stat = con.createStatement();
                    ResultSet res = stat.executeQuery(sql);
                    while(res.next()){
                        String KodePinjam = res.getString("kodepinjam");
                        String NIS = res.getString("nis");
                        String NamaSiswa = res.getString("nama");
                        String Kelas = res.getString("kelas");
                        String KodeBuku = res.getString("kodebuku");
                        String NamaBuku = res.getString("namabuku");
                        String Penerbit = res.getString("penerbit");
                        String TglPinjam = res.getString("tanggalpinjam");
                        String TglKembali = res.getString("tanggalkembali");
                        String Pengembalian = res.getString("tanggalpengembalian");
                        String Status = res.getString("statuspengembalian");
                        Object[] data = {KodePinjam, NIS, NamaSiswa, Kelas, KodeBuku, NamaBuku, Penerbit, TglPinjam, TglKembali, Pengembalian, Status };
                        Tabpin.addRow(data);
                    }
                    Tapin.getColumnModel().getColumn(0).setPreferredWidth(50);
                    Tapin.getColumnModel().getColumn(1).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(2).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(3).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(4).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(5).setPreferredWidth(100);
                    Tapin.getColumnModel().getColumn(6).setPreferredWidth(80);
                    Tapin.getColumnModel().getColumn(7).setPreferredWidth(80);
                    Tapin.getColumnModel().getColumn(7).setPreferredWidth(80);
                    Tapin.getColumnModel().getColumn(8).setPreferredWidth(50);
                    
                } catch (Exception ex){
                    JOptionPane.showMessageDialog(this,"Error: " + ex);
                }
            }
    /**
     * Creates new form pengembalian
     */
    public pengembalian() {
        initComponents();
        LoadData();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusPengembalian = new javax.swing.ButtonGroup();
        Nabuk = new javax.swing.JTextField();
        Pen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TglPin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TglKem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TglPem = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nasis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        KB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tapin = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        dendatxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btntepatwaktu = new javax.swing.JRadioButton();
        btnterlambat = new javax.swing.JRadioButton();
        btnhilang = new javax.swing.JRadioButton();
        CBKelas = new javax.swing.JComboBox();
        nis = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        kodepinjam = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        hilangtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Penerbit");

        TglPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TglPinActionPerformed(evt);
            }
        });

        jLabel7.setText("Tgl. Pinjam");

        jLabel8.setText("Tgl. Kembali (terjadwal)");

        TglKem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TglKemActionPerformed(evt);
            }
        });

        jLabel9.setText("NIS");

        jLabel10.setText("Tgl. Pengembalian");

        edit.setText("Update");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Data Pengembalian");

        jLabel2.setText("Nama");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Kelas");

        jLabel4.setText("Kode Buku");

        jLabel5.setText("Nama Buku");

        Tapin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tapin);

        jLabel11.setText("Denda");

        jLabel12.setText("Jika Terlambat Mengembalikan:");

        jLabel13.setText("Rp. 1000 / hari | Per Harga Buku Jika Hilang");

        jLabel14.setText("Status");

        statusPengembalian.add(btntepatwaktu);
        btntepatwaktu.setText("Tepat Waktu");
        btntepatwaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntepatwaktuActionPerformed(evt);
            }
        });

        statusPengembalian.add(btnterlambat);
        btnterlambat.setText("Terlambat");
        btnterlambat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnterlambatActionPerformed(evt);
            }
        });

        statusPengembalian.add(btnhilang);
        btnhilang.setText("Hilang");
        btnhilang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhilangActionPerformed(evt);
            }
        });

        CBKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "X", "XI", "XII" }));

        nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nisActionPerformed(evt);
            }
        });

        label.setText("Kode Pinjam");

        kodepinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodepinjamActionPerformed(evt);
            }
        });

        jLabel15.setText("Hilang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9)
                            .addComponent(label))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kodepinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntepatwaktu)
                                .addGap(18, 18, 18)
                                .addComponent(btnhilang))
                            .addComponent(TglPem)
                            .addComponent(CBKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nasis)
                            .addComponent(KB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nabuk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TglPin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TglKem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnterlambat)
                            .addComponent(nis))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel15))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(hilangtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                .addComponent(dendatxt, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addComponent(jLabel13)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodepinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nasis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(KB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit)
                            .addComponent(delete))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save)
                            .addComponent(jButton6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Nabuk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TglPin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TglKem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(1, 1, 1)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TglPem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(dendatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(btntepatwaktu)
                        .addComponent(btnhilang))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hilangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnterlambat)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TglPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TglPinActionPerformed

    }//GEN-LAST:event_TglPinActionPerformed

    private void TglKemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TglKemActionPerformed

    }//GEN-LAST:event_TglKemActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null,"Yakin untuk mengubah data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            String sql="update datakembali set kodepinjam=?,nis=?,nama=?,kelas=?,kodebuku=?,namabuku=?,penerbit=?,tanggalpinjam=?,tanggalkembali=?,tanggalpengembalian=?,statuspengembalian=?,denda=? where kodepinjam='"+kodepinjam.getText()+"'";
            PreparedStatement st=connection.prepareStatement(sql);
            if(confirm==0){
                try{
                    st.setString(1,kodepinjam.getText());
                    st.setString(2,nis.getText());
                    st.setString(3,Nasis.getText());
                    int kelas = CBKelas.getSelectedIndex();
                    String skelas;
                    if(kelas==0){st.setString(4,skelas="X");}
                    if(kelas==1){st.setString(4,skelas="XI");}
                    if(kelas==2){st.setString(4,skelas="XII");}
                    st.setString(5,KB.getText());
                    st.setString(6,Nabuk.getText());
                    st.setString(7,Pen.getText());
                    st.setString(8,TglPin.getText());
                    st.setString(9,TglKem.getText());
                    st.setString(10,TglPem.getText());
                    String btnStatus="";
                    if (btntepatwaktu.isSelected()){
                    st.setString(11,btntepatwaktu.getText());
                    //btnStatus = btntepatwaktu.getText();
                    dendatxt.setText("0");
                    st.setString(12,dendatxt.getText());
                    }if(btnhilang.isSelected()){
                    st.setString(11,btnhilang.getText());
                    st.setString(12,hilangtxt.getText());
                    }if(btnterlambat.isSelected()){
                    st.setString(11,btnterlambat.getText());
                    st.setString(12,dendatxt.getText());
                    //btnStatus = btnterlambat.getText();
                    }
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Update Data Sukses");
                    LoadData();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Update Data Gagal");
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak ada Data");
        }
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String x=kodepinjam.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            Statement stat=connection.createStatement();
            String sql2="delete from datapinjam where kodepinjam='"+x+"'";
            stat.executeUpdate(sql2);
            LoadData();
            int kelas = CBKelas.getSelectedIndex();
            String skelas = "";
            if(kelas==0){skelas="X";}
            if(kelas==1){skelas="XI";}
            if(kelas==2){skelas="XII";}
            String btnStatus="";
            String nilaidenda="0";
            if (btntepatwaktu.isSelected()){
                    btnStatus = btntepatwaktu.getText();
                    dendatxt.setText("0");
                }if(btnhilang.isSelected()){
                    btnStatus = btnhilang.getText();
                    nilaidenda= hilangtxt.getText();
                }if(btnterlambat.isSelected()){
                    btnStatus = btnterlambat.getText();
                    nilaidenda= dendatxt.getText();
                }
            String sqli=("insert into datakembali values('"+kodepinjam.getText()+"','"+nis.getText()+"','"+Nasis.getText()+"','"+skelas+"','"+KB.getText()+"','"+Nabuk.getText()+"','"+Pen.getText()+"','"+TglPin.getText()+"','"+TglKem.getText()+"','"+TglPem.getText()+"','"+btnStatus+"','"+nilaidenda+"')");
            stat.executeUpdate(sqli);
            JOptionPane.showMessageDialog(null,"Data Tersimpan");
            LoadData();
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        nis.setText(null);
        Nasis.setText(null);
        CBKelas.setSelectedIndex(0);
        KB.setText(null);
        Nabuk.setText("0");
        Pen.setText("0");
        TglPin.setText("0");
        TglKem.setText("0");
        TglPem.setText("0");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String x=kodepinjam.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            Statement stat=connection.createStatement();
            String sql="delete from datakembali where kodepinjam='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data Telah terhapus");
            LoadData();
            kodepinjam.setText(null);
            nis.setText(null);
            Nasis.setText(null);
            CBKelas.setSelectedIndex(0);
            KB.setText(null);
            Nabuk.setText(null);
            Pen.setText(null);
            TglPin.setText("0");
            TglKem.setText("0");
            TglPem.setText("0");
            statusPengembalian.clearSelection();
            dendatxt.setText(null);
            hilangtxt.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Koneksi Gagal"+e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Yakin untuk keluar?","Confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            this.dispose();
            new Menupetugas().show();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String x=JOptionPane.showInputDialog(null, "Masukkan Kode Pinjam");
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            Statement stat = connection.createStatement();
            String cari = "SELECT kodepinjam, nis, nama, kelas, kodebuku, namabuku, penerbit, tanggalpinjam, tanggalkembali from datapinjam WHERE kodepinjam='"+x+"'";
            ResultSet rsnya= stat.executeQuery(cari);
            if(rsnya.next()){
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(null,"Data ditemukan");
                LoadData();
                kodepinjam.setText(rsnya.getString(1));
                nis.setText(rsnya.getString(2));
                Nasis.setText(rsnya.getString(3));
                CBKelas.setSelectedItem(rsnya.getString(4));
                KB.setText(rsnya.getString(5));
                Nabuk.setText(rsnya.getString(6));
                Pen.setText(rsnya.getString(7));
                TglPin.setText(rsnya.getString(8));
                TglKem.setText(rsnya.getString(9));
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String x = JOptionPane.showInputDialog(null,"Masukkan Kode Pinjam");
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            Statement stat=connection.createStatement();
            String cari = "SELECT * FROM datakembali WHERE kodepinjam='"+x+"'";
            ResultSet rst=stat.executeQuery(cari);
            if(rst.next()){
                JOptionPane.showMessageDialog(null,"Data ditemukan");
                LoadData();
                System.out.print(rst.getString(1));
                kodepinjam.setText(rst.getString(1));
                nis.setText(rst.getString(2));
                Nasis.setText(rst.getString(3));
                CBKelas.setSelectedItem(rst.getString(4));
                KB.setText(rst.getString(5));
                Nabuk.setText(rst.getString(6));
                Pen.setText(rst.getString(7));
                TglPin.setText(rst.getString(8));
                TglKem.setText(rst.getString(9));
                TglPem.setText(rst.getString(10));
                if (rst.getString(11).equals("Tepat Waktu")){
                    btntepatwaktu.setSelected(true);
                    dendatxt.setEditable(false);
                    hilangtxt.setEditable(false);
                    }if(rst.getString(11).equals("Terlambat")){
                    btnterlambat.setSelected(true);
                    dendatxt.setText(rst.getString(12));
                    hilangtxt.setEditable(false);
                    }if(rst.getString(11).equals("Hilang")){
                    btnhilang.setSelected(true);
                    hilangtxt.setText(rst.getString(12));
                    dendatxt.setEditable(false);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Data tidak ada");
            }
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisActionPerformed

    private void btntepatwaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntepatwaktuActionPerformed
        dendatxt.setEditable(false);
        hilangtxt.setEditable(false);
        hilangtxt.setText("0");
        dendatxt.setText("0");
    }//GEN-LAST:event_btntepatwaktuActionPerformed

    private void btnterlambatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnterlambatActionPerformed
        dendatxt.setEditable(true);
        hilangtxt.setEditable(false);
        hilangtxt.setText("0");
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        try{
            java.util.Date TanggalKem = df.parse(TglKem.getText());
            java.util.Date TanggalPem = df.parse(TglPem.getText());
            
            long Hari1 = TanggalKem.getTime();
            long Hari2 = TanggalPem.getTime();
            long diff = Hari2 - Hari1;
            long lama = diff / (24*60*60*1000);
            long denda = lama * 1000;
            dendatxt.setText(Long.toString(denda));
        }catch(ParseException e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btnterlambatActionPerformed

    private void btnhilangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhilangActionPerformed
        dendatxt.setEditable(false);
        hilangtxt.setEditable(true);
        dendatxt.setText("0");
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
        Calendar cal = Calendar.getInstance();
        TglPem.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_btnhilangActionPerformed

    private void kodepinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodepinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodepinjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBKelas;
    private javax.swing.JTextField KB;
    private javax.swing.JTextField Nabuk;
    private javax.swing.JTextField Nasis;
    private javax.swing.JTextField Pen;
    private javax.swing.JTable Tapin;
    private javax.swing.JTextField TglKem;
    private javax.swing.JTextField TglPem;
    private javax.swing.JTextField TglPin;
    private javax.swing.JRadioButton btnhilang;
    private javax.swing.JRadioButton btntepatwaktu;
    private javax.swing.JRadioButton btnterlambat;
    private javax.swing.JButton delete;
    private javax.swing.JTextField dendatxt;
    private javax.swing.JButton edit;
    private javax.swing.JTextField hilangtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodepinjam;
    private javax.swing.JLabel label;
    private javax.swing.JTextField nis;
    private javax.swing.JButton save;
    private javax.swing.ButtonGroup statusPengembalian;
    // End of variables declaration//GEN-END:variables
}
