/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tsukinami
 */
public class petugas extends javax.swing.JFrame {

    /**
     * Creates new form petugas
     */    
   
    public petugas() {
        initComponents();
        setLocationRelativeTo(null);
        Load();
        LoadData();
    }
    private DefaultTableModel TabPetugas;
    Connection Con;
    
    private void LoadData(){
        Object kolom[] = {"NIK","NAMA PETUGAS","JENIS KELAMIN","JABATAN","KEHADIRAN","ABSEN","BIAYA TRANSPORT","TUNJANGAN","GAJI"};
        TabPetugas = new DefaultTableModel(null, kolom);
        TabPetug.setModel(TabPetugas);
        jScrollPane1.getViewport().add(TabPetug,null);
        
        try{
            Con = null;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            String sql = "" + "SELECT * from datapetugas";
            Statement stat=con.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while(res.next()){
                String NIK = res.getString("NIK");
                String NamaPetugas= res.getString("namaPetugas");
                String JenisKelamin= res.getString("jenisKelamin");
                String Jabatan= res.getString("Jabatan");
                String Absen= res.getString("Absen");
                String JumlahAbsen= res.getString("jumlahAbsen");
                String BiayaTransport= res.getString("biayaTransport");
                String Tunjangan= res.getString("Tunjangan");
                String Gaji= res.getString("Gaji");
                Object[] data = {NIK, NamaPetugas, JenisKelamin, Jabatan, Absen, JumlahAbsen, BiayaTransport, Tunjangan,Gaji};
                TabPetugas.addRow(data);
            }
            TabPetug.getColumnModel().getColumn(0).setPreferredWidth(50);
            TabPetug.getColumnModel().getColumn(1).setPreferredWidth(110);
            TabPetug.getColumnModel().getColumn(2).setPreferredWidth(50);
            TabPetug.getColumnModel().getColumn(3).setPreferredWidth(80);
            TabPetug.getColumnModel().getColumn(4).setPreferredWidth(90);
            TabPetug.getColumnModel().getColumn(5).setPreferredWidth(60);
            TabPetug.getColumnModel().getColumn(6).setPreferredWidth(100);
            TabPetug.getColumnModel().getColumn(7).setPreferredWidth(100);
            TabPetug.getColumnModel().getColumn(8).setPreferredWidth(80);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error: " + ex);
        }
    }
    
    private void Load(){
        nik.setText(null);
        namapetugas.setText(null);
        RBJenisKelamin.clearSelection();
        jabatan.setText(null);
        absen.setText("0");
        jumlahabsen.setText("0");
        biayatransport.setText("0");
        tunjangan.setText("0");
        gaji.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RBJenisKelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        namapetugas = new javax.swing.JTextField();
        jabatan = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        jumlahabsen = new javax.swing.JTextField();
        biayatransport = new javax.swing.JTextField();
        tunjangan = new javax.swing.JTextField();
        gaji = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabPetug = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        delbutton = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        RBLaki = new javax.swing.JRadioButton();
        RBPerempuan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(721, 700));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Data Petugas");

        jLabel2.setText("NIP");

        jLabel3.setText("Nama Petugas");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Jabatan");

        jLabel6.setText("Kehadiran");

        jLabel7.setText("Jumlah Absen");

        jLabel8.setText("Biaya Transport");

        jLabel9.setText("Tunjangan");

        jLabel10.setText("Gaji");

        nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikActionPerformed(evt);
            }
        });

        namapetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapetugasActionPerformed(evt);
            }
        });

        TabPetug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Petugas", "Jenis Kelamin", "Jabatan", "Kehadiran", "Jumlah Absen", "Biaya Transport", "Tunjangan", "Gaji"
            }
        ));
        jScrollPane1.setViewportView(TabPetug);
        if (TabPetug.getColumnModel().getColumnCount() > 0) {
            TabPetug.getColumnModel().getColumn(1).setMinWidth(30);
            TabPetug.getColumnModel().getColumn(1).setMaxWidth(30);
        }

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tabel Petugas");

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        editbtn.setText("Update");
        editbtn.setToolTipText("");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        refreshbtn.setText("Refresh");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });

        delbutton.setText("Delete");
        delbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbuttonActionPerformed(evt);
            }
        });

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        jButton1.setText("SignUp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        RBJenisKelamin.add(RBLaki);
        RBLaki.setText("Laki-Laki");
        RBLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBLakiActionPerformed(evt);
            }
        });

        RBJenisKelamin.add(RBPerempuan);
        RBPerempuan.setText("Perempuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gaji)
                                .addComponent(namapetugas)
                                .addComponent(jabatan)
                                .addComponent(absen)
                                .addComponent(jumlahabsen)
                                .addComponent(biayatransport)
                                .addComponent(nik)
                                .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RBLaki)
                                .addGap(18, 18, 18)
                                .addComponent(RBPerempuan)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(refreshbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton1))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(295, 295, 295))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namapetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(RBPerempuan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(absen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahabsen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(biayatransport, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchbtn)
                            .addComponent(refreshbtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editbtn)
                            .addComponent(delbutton))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savebtn)
                            .addComponent(exitbtn))
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namapetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapetugasActionPerformed

    private void nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
            // TODO add your handling code here:
        String x = JOptionPane.showInputDialog(null,"Masukkan Nomor Petugas");
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            Statement stat=connection.createStatement();
            String cari = "SELECT * FROM datapetugas WHERE NIK='"+x+"'";
            ResultSet rst=stat.executeQuery(cari);
            if(rst.next()){
                JOptionPane.showMessageDialog(null,"Data ditemukan");
                LoadData();
                System.out.print(rst.getString(1));
                nik.setText(rst.getString(1));
                namapetugas.setText(rst.getString(2));
                if (rst.getString(3).equals("Laki-Laki")){
                    RBLaki.setSelected(true);
                    }else{
                    RBPerempuan.setSelected(true);
                    }
                jabatan.setText(rst.getString(4));
                absen.setText(rst.getString(5));
                jumlahabsen.setText(rst.getString(6));
                biayatransport.setText(rst.getString(7));
                tunjangan.setText(rst.getString(8));
                gaji.setText(rst.getString(9));
            }else{
                JOptionPane.showMessageDialog(null,"Data tidak ada");
            }
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null,"Yakin untuk mengubah data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            String sql="update datapetugas set NIK=?,namaPetugas=?,jenisKelamin=?,Jabatan=?,Absen=?,jumlahAbsen=?,BiayaTransport=?,Tunjangan=?,Gaji=? where NIK='"+nik.getText()+"'";
            PreparedStatement st=connection.prepareStatement(sql);
            if(confirm==0){
                try{
                    st.setString(1,nik.getText());
                    st.setString(2,namapetugas.getText());
                    if (RBLaki.isSelected()){
                    st.setString(3,RBLaki.getText());
                    }if(RBPerempuan.isSelected()){
                    st.setString(3,RBPerempuan.getText());
                    }
                    st.setString(4,jabatan.getText());
                    st.setString(5,absen.getText());
                    st.setString(6,jumlahabsen.getText());
                    st.setString(7,biayatransport.getText());
                    st.setString(8,tunjangan.getText());
                    st.setString(9,gaji.getText());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Update Data Sukses");
                    LoadData();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Update Data Gagal");
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak ada Data");
        }
        
    }//GEN-LAST:event_editbtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        // TODO add your handling code here:
        Load();
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void delbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbuttonActionPerformed
        // TODO add your handling code here:
         String x=nik.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");    
            Statement stat=connection.createStatement();
            String sql="delete from datapetugas where NIK='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data Telah terhapus");
            LoadData();
            nik.setText(null);
            namapetugas.setText(null);
            RBJenisKelamin.clearSelection();
            jabatan.setText(null);
            absen.setText("0");
            jumlahabsen.setText("0");
            biayatransport.setText("0");
            tunjangan.setText("0");
            gaji.setText("0");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Koneksi Gagal"+e);
        }
    }//GEN-LAST:event_delbuttonActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        String x=nik.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");    
            Statement stat=connection.createStatement();
             String btnJenisKelamin="";
                if (RBLaki.isSelected()){
                    btnJenisKelamin = RBLaki.getText();
                }else{
                    btnJenisKelamin = RBPerempuan.getText();
                }
            String sqli=("insert into datapetugas values('"+nik.getText()+"','"+namapetugas.getText()+"','"+btnJenisKelamin+"','"+jabatan.getText()+"','"+absen.getText()+"','"+jumlahabsen.getText()+"','"+biayatransport.getText()+"','"+tunjangan.getText()+"','"+gaji.getText()+"')");
            stat.executeUpdate(sqli);
            JOptionPane.showMessageDialog(null,"Data Tersimpan");
            LoadData();
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Yakin untuk keluar?","Confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            this.dispose();
            new admin().show();
        }
    }//GEN-LAST:event_exitbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new signup().show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RBLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBLakiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RBJenisKelamin;
    private javax.swing.JRadioButton RBLaki;
    private javax.swing.JRadioButton RBPerempuan;
    private javax.swing.JTable TabPetug;
    private javax.swing.JTextField absen;
    private javax.swing.JTextField biayatransport;
    private javax.swing.JButton delbutton;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField gaji;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jabatan;
    private javax.swing.JTextField jumlahabsen;
    private javax.swing.JTextField namapetugas;
    private javax.swing.JTextField nik;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField tunjangan;
    // End of variables declaration//GEN-END:variables
}
